# Generated by Django 6.0 on 2026-01-14 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coursetemplate_usercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AircraftModelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PASSENGER', 'Passenger'), ('CARGO', 'Cargo'), ('COMBINED', 'Combined Passenger/Cargo'), ('SPECIAL', 'Special Mission')], max_length=20)),
                ('icao_code', models.CharField(blank=True, max_length=10)),
                ('iata_code', models.CharField(blank=True, max_length=3)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.aircraftmanufacturer')),
            ],
            options={
                'verbose_name': 'Aircraft Model Group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=20, unique=True)),
                ('registration', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('msn', models.CharField(blank=True, max_length=50, verbose_name='Manufacturer Serial Number')),
                ('engine_type', models.CharField(blank=True, max_length=100)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Under Maintenance'), ('STORED', 'Stored'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('maintenix_inventory_id', models.CharField(help_text='Inventory ID from Maintenix system', max_length=255, unique=True)),
                ('maintenix_url_template', models.TextField(help_text='URL template for accessing aircraft in Maintenix. Use {inventory_id} as placeholder.')),
                ('active', models.BooleanField(default=True)),
                ('model_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='store.aircraftmodelgroup')),
            ],
            options={
                'verbose_name_plural': 'Aircraft',
                'ordering': ['tail_number'],
            },
        ),
        migrations.CreateModel(
            name='AircraftScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tasks_scraped', models.IntegerField(default=0)),
                ('work_packages_scraped', models.IntegerField(default=0)),
                ('errors_encountered', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('log_file_path', models.CharField(blank=True, max_length=500)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.aircraft')),
                ('aircraft_model_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.aircraftmodelgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=500)),
                ('task_id', models.CharField(db_index=True, max_length=100)),
                ('config_position', models.CharField(blank=True, max_length=200)),
                ('must_be_removed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('soft_deadline', models.BooleanField(default=False)),
                ('inventory', models.CharField(max_length=200)),
                ('task_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DEFERRED', 'Deferred')], default='OPEN', max_length=20)),
                ('work_type', models.CharField(choices=[('LINE', 'Line Maintenance'), ('HANGAR', 'Hangar Maintenance'), ('SHOP', 'Shop Maintenance'), ('INSPECTION', 'Inspection'), ('MODIFICATION', 'Modification'), ('TROUBLESHOOTING', 'Troubleshooting'), ('OTHER', 'Other')], default='LINE', max_length=20)),
                ('originator', models.CharField(blank=True, max_length=200)),
                ('task_priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('ROUTINE', 'Routine')], default='MEDIUM', max_length=20)),
                ('schedule_priority', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('ROUTINE', 'Routine')], max_length=20)),
                ('driving_task_name', models.CharField(blank=True, max_length=500)),
                ('driving_task_id', models.CharField(blank=True, max_length=100)),
                ('etops_significant', models.BooleanField(default=False, verbose_name='ETOPS Significant')),
                ('work_package_name', models.CharField(blank=True, max_length=500)),
                ('work_package_id', models.CharField(blank=True, max_length=100)),
                ('work_package_number', models.CharField(blank=True, max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('marked_for_deletion', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_tasks', to='store.aircraft')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_tasks', to=settings.AUTH_USER_MODEL)),
                ('scraped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scraped_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_tasks', to='store.aircraftscrapingsession')),
            ],
            options={
                'ordering': ['due_date', 'task_priority'],
            },
        ),
        migrations.CreateModel(
            name='OpenWorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_package_name', models.CharField(max_length=500)),
                ('work_package_id', models.CharField(db_index=True, max_length=100)),
                ('inventory', models.CharField(max_length=200)),
                ('work_package_number', models.CharField(max_length=100)),
                ('work_package_status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('request_parts', models.BooleanField(default=False, verbose_name='Request Parts Required')),
                ('work_location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('schedule_priority', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('driving_task_name', models.CharField(blank=True, max_length=500)),
                ('driving_task_id', models.CharField(blank=True, max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('marked_for_deletion', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='store.aircraft')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_work_packages', to=settings.AUTH_USER_MODEL)),
                ('scraped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scraped_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_work_packages', to='store.aircraftscrapingsession')),
            ],
            options={
                'ordering': ['start_date', 'schedule_priority'],
            },
        ),
        migrations.CreateModel(
            name='AircraftAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('OVERDUE_TASK', 'Overdue Task'), ('OVERDUE_WORK_PACKAGE', 'Overdue Work Package'), ('UPCOMING_DUE_DATE', 'Upcoming Due Date'), ('CRITICAL_TASK', 'Critical Task'), ('AIRCRAFT_CHECK_DUE', 'Aircraft Check Due'), ('SYSTEM', 'System Alert')], max_length=50)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='store.aircraft')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.opentask')),
                ('related_work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.openworkpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opentask',
            index=models.Index(fields=['task_id'], name='store_opent_task_id_67bdad_idx'),
        ),
        migrations.AddIndex(
            model_name='opentask',
            index=models.Index(fields=['task_status'], name='store_opent_task_st_8dfdfd_idx'),
        ),
        migrations.AddIndex(
            model_name='opentask',
            index=models.Index(fields=['due_date'], name='store_opent_due_dat_56cb24_idx'),
        ),
        migrations.AddIndex(
            model_name='opentask',
            index=models.Index(fields=['aircraft', 'task_status'], name='store_opent_aircraf_8c85d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opentask',
            unique_together={('aircraft', 'task_id')},
        ),
        migrations.AddIndex(
            model_name='openworkpackage',
            index=models.Index(fields=['work_package_id'], name='store_openw_work_pa_aa5a65_idx'),
        ),
        migrations.AddIndex(
            model_name='openworkpackage',
            index=models.Index(fields=['work_package_status'], name='store_openw_work_pa_25dfbe_idx'),
        ),
        migrations.AddIndex(
            model_name='openworkpackage',
            index=models.Index(fields=['start_date'], name='store_openw_start_d_31784f_idx'),
        ),
        migrations.AddIndex(
            model_name='openworkpackage',
            index=models.Index(fields=['aircraft', 'work_package_status'], name='store_openw_aircraf_e78dd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openworkpackage',
            unique_together={('aircraft', 'work_package_id')},
        ),
    ]
