# Generated by Django 6.0 on 2026-01-30 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_aircraftmanufacturer_aircraftmodelgroup_aircraft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftFlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('previous_flight_number', models.CharField(blank=True, max_length=10, verbose_name='PFLT')),
                ('previous_flight_location', models.CharField(blank=True, max_length=3, verbose_name='FROM')),
                ('scheduled_arrival_time', models.TimeField(blank=True, null=True, verbose_name='STA')),
                ('equipment_type', models.CharField(blank=True, max_length=50, verbose_name='EQPT')),
                ('previous_tail_scheduled', models.CharField(blank=True, max_length=20, verbose_name='PTAIL')),
                ('current_tail_scheduled', models.CharField(max_length=20, verbose_name='TAIL')),
                ('current_flight_number', models.CharField(max_length=10, verbose_name='FLT')),
                ('flight_destination', models.CharField(max_length=3, verbose_name='DEST')),
                ('scheduled_departure_time', models.TimeField(blank=True, null=True, verbose_name='STD')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_schedules', to='store.aircraft')),
            ],
            options={
                'verbose_name': 'Aircraft Flight Schedule',
                'verbose_name_plural': 'Aircraft Flight Schedules',
                'ordering': ['flight_date', 'scheduled_departure_time'],
                'indexes': [models.Index(fields=['flight_date'], name='store_aircr_flight__dd12d3_idx'), models.Index(fields=['current_tail_scheduled'], name='store_aircr_current_b44072_idx'), models.Index(fields=['current_flight_number'], name='store_aircr_current_e3cd2d_idx')],
            },
        ),
    ]
